import type { Metadata } from "next";
import { /* Geist, Geist_Mono, */ Comforter } from "next/font/google";
import "./globals.css";

const comforter = Comforter({
  weight: "400",
  // variable: "--font-abeezee",
  // subsets: ["latin"],
});

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.jpg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${comforter.className}`}>{children}</body>
    </html>
  );
}
